# A Supabase project configuration file.
# Learn more: https://supabase.com/docs/reference/config

[project]
# Project ID from the Supabase dashboard
# id = "your-project-id"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API.
schemas = ["public", "storage", "storage_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure.
max_rows = 1000

[functions]
# To deploy to the project, set serve.project_ref to your Supabase project Reference ID.
# serve.project_ref = "your-project-ref"
# serve.hostname = "localhost"
serve.port = 54321

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

[inbucket]
# Port to use for the email testing server's SMTP port.
smtp_port = 54324
# Port to use for the email testing server's POP3 port.
pop3_port = 54325
# Port to use for the email testing server's web UI.
ui_port = 54326

[storage]
# The maximum file size allowed (in bytes).
file_size_limit = 52428800

[auth]
# The base URL of your website.
site_url = "http://localhost:3000"
# A list of URLs that can redirect users after they authenticate.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for. Defaults to 1 hour.
jwt_expiry = 3600
# If disabled, new users will need to confirm their email address before signing in.
enable_signup = true

# Configure the storage key used for the local development storage service. Required for file storage and image transformation to work.
[storage.runtime]
storage_backend = "file"

# Configure email templates for Auth
[auth.email.template.invite]
subject = "You've been invited"
content_path = "email-templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Email"
content_path = "email-templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = "email-templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = "email-templates/magic-link.html"

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = "email-templates/email-change.html"

[auth.sms.template.recovery]
body = "Your WatanHub verification code is: {{ .Code }}"

[auth.sms.template.verification]
body = "Your WatanHub verification code is: {{ .Code }}"

# Configure environment variables for the Edge Functions
[functions.gemini-proxy.environment]
GEMINI_API_KEY = "your-gemini-api-key"
# You would set this in production with: supabase secrets set GEMINI_API_KEY=your-actual-key 